[package]
name = "assfonts"
version = "0.1.0"
edition = "2024"
default-run = "assfonts_gui"

[features]
default = ["desktop", "cli"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]
# The feature that are only required for the server = ["dioxus/server"] build target should be optional and only enabled in the server = ["dioxus/server"] feature
server = ["dioxus/server"]
cli = ["clap"]
bundle = []

[[bin]]
name = "assfonts_gui"
path = "src/bin/gui.rs"
required-features = ["desktop"]

[dependencies]
clap = { version = "4.6.0", features = ["derive"], optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.18"
walkdir = "2.5.0"
ttf-parser = "0.25.1"
allsorts = "0.16.1"
rayon = "1.10.0"
dashmap = "6.1.0"
color-eyre = "0.6"
dioxus = { version = "0.7.1", features = ["router"] }
dirs = "6.0.0"
rfd = "0.17.2"
tokio = { version = "1", features = ["time"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
