[package]
name = "assfonts"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.18"
walkdir = "2.5.0"
ttf-parser = "0.25.1"
allsorts = "0.17.0"
rayon = "1.10.0"
dashmap = "6.1.0"
color-eyre = "0.6"
encoding_rs = "0.8.35"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
