[application]

[web.app]

# HTML title tag content
title = "assfonts"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
# The list of files to include in the bundle. These can contain globs.
identifier = "com.mycompany"
publisher = "MyCompany"
resources = ["assets/dx-components-theme.css"]