/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const Tab: typeof import('primevue/tab')['default']
  const TabList: typeof import('primevue/tablist')['default']
  const TabPanel: typeof import('primevue/tabpanel')['default']
  const TabPanels: typeof import('primevue/tabpanels')['default']
  const Tabs: typeof import('primevue/tabs')['default']
  const Toast: typeof import('primevue/toast')['default']
}